steps:
  - plugins:
      - docker#v5.8.0:
          image: "armory/armory-cli"
          always-pull: true
          command: ["armory deploy start --file armory-deploy.yml -c NB7l5woTJ3P8SjUQYe7yNQxzSZkrvDLA -s z8EkU0esFgUG7EWj-VyUmL3YiQJIq39S1VR6n1xV9EVE8OirLqk8MJerrMeRGttl"]
